### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by cliveportman** [solspace/craft-freeform#323]
**Describe the bug or issue you're experiencing**
Unable to install.

**Steps to reproduce**

1. `composer require solspace/craft-freeform`
```
- solspace/craft-freeform[3.13.0, ..., 3.13.7] require symfony/finder ^2.8|^3.0|^4.0|^5.0 -> found symfony/finder[v2.8.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
- Root composer.json requires solspace/craft-freeform ^3.13 -> satisfiable by solspace/craft-freeform[3.13.0, ..., 3.13.7].
```

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.38
- Freeform Version:
- Freeform Edition:
- Fresh Install or Upgrade: fresh install

**Comment by kjmartens** [comment]
Hi @cliveportman, can you attach your main composer.json and composer.lock files for review? 🙂

**Comment by kjmartens** [comment]
Hi again @cliveportman,

We've updated the dependencies in the repo now. Would you be able to update your version to `dev-master as 3.13.7.1` and see if it works? 🙂

**Comment by kjmartens** [comment]
Thanks @mauricioarangoosorio. I'm just going to make a note here that after trying the update, you also received these new errors:

```
Problem 1
    - phpoffice/phpspreadsheet[1.6.0, ..., 1.8.2] require php ^5.6|^7.0 -> your php version (8.1.3; overridden via config.platform, actual: 7.4.28) does not satisfy that requirement.
    - phpoffice/phpspreadsheet[1.9.0, ..., 1.12.0] require php ^7.1 -> your php version (8.1.3; overridden via config.platform, actual: 7.4.28) does not satisfy that requirement.
    - phpoffice/phpspreadsheet[1.13.0, ..., 1.14.1] require php ^7.2 -> your php version (8.1.3; overridden via config.platform, actual: 7.4.28) does not satisfy that requirement.
    - phpoffice/phpspreadsheet[1.15.0, ..., 1.22.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - phpoffice/phpspreadsheet 1.23.0 requires psr/simple-cache ^1.0 || ^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - solspace/craft-freeform 4.0.0-beta.3 requires phpoffice/phpspreadsheet ^1.6.0 -> satisfiable by phpoffice/phpspreadsheet[1.6.0, ..., 1.23.0].
    - Root composer.json requires solspace/craft-freeform 4.0.0-beta.3 -> satisfiable by solspace/craft-freeform[4.0.0-beta.3].
```

We'll check into this shortly...

**Comment by mauricioarangoosorio** [comment]
Thanks a lot!

**Comment by kjmartens** [comment]
@mauricioarangoosorio From what I can see, `phpoffice/phpspreadsheet 1.23.0` (required by Freeform) is stuck on `^1.0|^2.0` of `psr/simple-cache`, while `illuminate/contracts` (called by `illuminate/collections`, which is called by `craftcms/cms`) allows `^1.0|^2.0|^3.0`. This ultimately then becomes out of our hands and a problem that must be sorted out by the `phpoffice/phpspreadsheet` dependency. 😬 

I assume since you already have Craft installed (of course) you would have 3.0 of the dependency already, and your current approach with locked Craft and plugins versions, and installing Freeform this way might then fail on an issue like this.

Until either the dependency sorts this out (or we have to temporarily remove the dependency and disable Excel exporting submissions), can you try this approach and see if it works around the issue?

1. Delete the Craft `vendor` folder.
2. Update your main composer.json file to have this (note addition of Freeform):
```
  "require": {
    "craftcms/cms": "4.0.0-beta.4",
    "craftcms/feed-me": "5.0.0-beta.2",
    "craftcms/redactor": "3.0.0-beta.2",
    "ryssbowh/craft-emails": "2.0.0-beta.3",
    "solspace/craft-freeform": "^4.0.0-beta.3",
    "spatie/craft-ray": "2.0",
    "vlucas/phpdotenv": "^5.4.0"
  },
```
3. In your CLI, run `composer install`.

See if that works for you. I believe it would then look at all packages and choose the right combination that satisfies all.

Another consideration would be to update some of your dependencies like Craft and such to include `^`. I'm not 100% sure, but it might also have resolved this issue while running `composer require solspace/craft-freeform`:

```
  "require": {
    "craftcms/cms": "^4.0.0-beta.4",
    "craftcms/feed-me": "^5.0.0-beta.2",
    "craftcms/redactor": "^3.0.0-beta.2",
    "ryssbowh/craft-emails": "^2.0.0-beta.3",
    "spatie/craft-ray": "^2.0",
    "vlucas/phpdotenv": "^5.4.0"
  },
```

**Comment by kjmartens** [comment]
Glad that resolved it for you, @mauricioarangoosorio

**Comment by kjmartens** [comment]
@cliveportman Ok then to confirm, everything is good now? 🙂

**Comment by cliveportman** [comment]
Yep. Sorted. Thanks.
