### ISSUE TITLE
Column not found: 1054 Unknown column 'field_260' in 'field list'

### ISSUE THREAD

**Issue by sarlahooda** [solspace/craft-freeform#330]
```

Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_260' in 'field list'
The SQL being executed was: INSERT INTO `craft_freeform_submissions` (`userId`, `formId`, `statusId`, `incrementalId`, `token`, `ip`, `isSpam`, `field_259`, `field_319`, `field_258`, `field_311`, `field_310`, `field_323`, `field_312`, `field_282`, `field_291`, `field_287`, `field_260`, `field_313`, `field_277`, `field_271`, `field_278`, `field_283`, `field_292`, `field_288`, `field_267`, `field_315`, `field_279`, `field_280`, `field_284`, `field_293`, `field_289`, `field_268`, `field_274`, `field_273`, `field_285`, `field_290`, `field_300`, `field_302`, `field_..............
```

field 260 is not present in the database, i inspected the database.

"craftcms/cms": "3.7.38"
"solspace/craft-freeform": "3.13.7"

**Comment by kjmartens** [comment]
Hi @sarlahooda,

Sorry about this. The issue is likely caused by too many fields and your `freeform_submissions` database table running out of room for columns. In Freeform 3, all forms share a single database table for submissions. We've made a number of improvements to this over the last year, but some customers may still max out on fields. This likely wouldn't ever happen in Freeform 4 (for Craft 4), as we have changed/improved it to use individual tables for each form.

To resolve this issue in Freeform 3, you will first need to delete any fields created in the `freeform_fields` table but not the `freeform_submissions` table (you can cross-reference by the field IDs). So first, remove the field(s) from the form builder and delete them from the Freeform -> Fields page in the CP.

 Then, inside your database, manually adjust some existing field columns in the `freeform_submissions` table from `VARCHAR` to `TEXT`. When this is done, you can try creating more fields again and be sure they are appearing in both the `freeform_fields` and `freeform_submissions` tables.

It's also worth noting that if you aren't already aware, fields are shared across all forms and you should be able to reuse many common fields like Name, Email, Phone, etc, rather than creating multiple versions of it. I assume, however, that you're running into this issue because you have complex forms with many questions, etc.

Please let me know if you need any further assistance with this. 🙂
