### ISSUE TITLE
Custom Attributes: "submitClass" should replace the default, not be additive

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-freeform#357]
**Describe the bug or issue you're experiencing**
Custom attributes set on a form should override the classes. They're currently being added to the defaults:

**Steps to reproduce**

Add a form with the Tailwind template, then embed a form using

```
{{ craft.freeform.form( form.handle, ).render({ submitClass: 'btn-red' }) }}
```

**Expected behavior**
The submit button should only have the class `btn-red`. Instead, it has `bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2 btn btn-red`

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.43
- Freeform Version: 3.13.10
- Freeform Edition:Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @darylknight,

I appreciate your feedback on this, but currently, it needs to work this way. With all of the puzzle pieces (attributes coming from form builder, formatting templates and other areas), it's expected to work this way. Even if we wanted to change this to replace instead of being additive, it would likely break hundreds of other customers' installs.

Instead, you should create a copy of the Tailwind template to have your custom one. Then you won't run into issues like this. It's also worth noting that we will be making some further improvements to this area of Freeform in the future that will be helpful in situations like this. 🙂

**Comment by kjmartens** [comment]
I'm just rereading what is in the docs now, and see that it says "overrides all classes", etc. Let me review that and see if it's an issue with the wording in the docs. It could just be a poor choice of wording in the docs.

**Comment by kjmartens** [comment]
As I mentioned before, whatever the case, we cannot change things now that many are relying on the current behavior. It's possible that at one point this was supposed to override classes, but somewhere along the way (perhaps the addition of the **Attribute Editor** in the form builder, or maybe long before that), the behavior was changed to accommodate that.

At any rate, I will update the documentation. 🙂

**Comment by darylknight** [comment]
No problem, thanks for the info Kelsey :)
