### ISSUE TITLE
The freeform-stripe-styling inline script causing issues if using Vue or React

### ISSUE THREAD

**Issue by a-am** [solspace/craft-freeform#367]
We have toggled the Behavior Freeform Script Insertion Location setting to output in the footer so we can use forms in Vue or React. However there is still a small script for `freeform-stripe-styling` that is being output inline instead of in the footer like the settings state.

**Steps to reproduce**

1. Set Form Behavior Freeform Script Insertion Location setting to Footer
2. Output form on a page
3. Inspect DOM to find `freeform-stripe-styling` script above first input.

**Expected behavior**
With the Form Behavior Freeform Script Insertion Location set to Footer I would expect any script for the form to be loaded in the footer.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft CMS 3.7.11
- Freeform Version: 3.13.12
- Freeform Edition: Pro
- Fresh Install or Upgrade:  Fresh Install

**Comment by kjmartens** [comment]
Sorry for the delay @a-am,

Can you confirm if you're using a default formatting template included with Freeform? We include that snippet there because there's no other way to automate this better. But you can certainly create your own formatting template with that code removed and placed wherever you like in your regular template. 🙂

**Comment by a-am** [comment]
@kjmartens thanks for responding.  Yes I can confirm we are using the sample formatting template.  I will give your suggestion a try. Thank you.
