### ISSUE TITLE
Cannot access Export Profiles

### ISSUE THREAD

**Issue by chrismlusk** [solspace/craft-freeform#426]
**Describe the bug or issue you're experiencing**

When attempting to load the `/admin/freeform/export/profiles` route, I get the following error:

```
Solspace\Freeform\Models\Pro\ExportProfileModel::getFormModel(): Return value must be of type Solspace\Freeform\Models\FormModel, null returned
```

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.50
- Freeform Version: 3.13.17
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble @chrismlusk. This likely is happening because you have an export profile for a form that no longer exists. Can you manually check the `freeform_export_profiles` table database and delete the row with a form ID that no longer exists? It should resolve this issue. Not sure how this happened, as Freeform does clear these when a form is deleted. 🙂

**Comment by chrismlusk** [comment]
Aha, that did the trick. Thank you!
