### ISSUE TITLE
Previous / Next button functionality

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-freeform#457]
**Describe the bug or issue you're experiencing**
Using the default Bootstrap 5 templates (no custom Javascript), using multi-page forms.

2 bugs:

1. If you're looking at Page 2 of a form (for example), with required fields, and you don't fill all of the fields in, then click "Previous", you cannot go back - you must fill in all required fields first. Ok, that's kind of expected. If you then fill in the rest of the required fields and click "Next", the form takes you back to Page 1, instead of Page 3. It should take you to Page 3 because that's the button you clicked.

2. So now you're back on Page 1. if you click Next, to go back to Page 2, all the fields you just filled in are now blank. These should contain all the values you filled in earlier.

**Expected behavior**
- The form should take you to Page 3, not back to Page 1.
- When you navigate around a form, it should retain all the values you previously filled in.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.2.4
- Freeform Version: 4.0.3
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @darylknight,

Thanks for reporting these.

For both **1** & **2**, current page form data is not saved when clicking the **Previous** button, so this is somewhat expected behavior. That said, we're going to see if we can adjust the behavior to save it.

As for forcing you to enter required values before allowing the previous page, please be aware that Freeform does in fact, disable its own built-in validation when the **Previous** button is clicked by the user, but what you are experiencing here is browser validation when using the `required` attribute. There is no way for Freeform or any other software to circumvent this, which is why we aren't the biggest fans of using the browser validation on forms.

I totally get that the browser behavior, mixed with Freeform's behavior of not saving data on Previous submit makes for a very awkward experience for the user, however. We'll see if we can get Freeform to save the data when going backwards though. 🙂 

As for the issue of clicking Previous initially, and then later clicking Next and it brings you to Page 1 instead of Page 3, that's something we should be able to address shortly. 🙂

**Comment by darylknight** [comment]
Thanks for the detailed reply Kelsey.

1 - We always use the `useRequiredAttribute: true` in our form code, because otherwise it just doesn't validate the fields at all and allows the user to submit blank required fields on normal forms. Perhaps that's a bug? I can do some more testing if that isn't how it's meant to work.

Sounds like the last one is an actual bug, and it's the most important one to fix. I think they can live with having to fill in fields before going back - but clicking Next and being taken to Previous is pretty wonky. Thanks!

**Comment by kjmartens** [comment]
The previous/next issue should be resolved in Freeform 4.0.5 now. 🙂
