### ISSUE TITLE
Formatting template doesn't seem to be optional when using AJAX

### ISSUE THREAD

**Issue by thisisjamessmith** [solspace/craft-freeform#499]
**Describe the bug or issue you're experiencing**

I'm using a semi-manual rendering process and as such don't want clients to be able to choose their own formatting template. I've disabled access to the Solspace templates in the settings, and have also deliberately not specified any custom formatting templates (there will only ever be one, why get them to select it!). I'm submitting forms via AJAX, and get the following error message: `Form template 'flexbox.html' not found` - even though no formatting template has been assigned to the form.

If I enable the formatting template selection and select a template then it works ok (though the selection is completely redundant as I'm using a manual rendering process using my own Twig template).

If I disable the AJAX checkbox and use a normal POST request with page refresh it works ok.

I am not using Solspace's bundled JavaScript at all - I'm making the AJAX request from my own JS, which is applied to the template conditionally according to the AJAX checkbox.

**Steps to reproduce**

1. Create a form and do not assign any formatting template to it. 
2. Switch off Solspace's JS bundle
3. Enable AJAX via the checkbox and create a simple ajax/fetch function to do the submission
4. Submit

**Craft & Plugin Info:**

- Craft Version: 4.3.1
- Freeform Version: 4.0.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: fairly fresh

**Comment by kjmartens** [comment]
Hi @thisisjamessmith,

Sorry for the delay... 

Freeform is designed to force the usage of formatting templates, though I see there is a scenario where this can be worked around. My understanding is that in order to make AJAX for multi-page forms (as well as Success Behavior handling), Freeform needs to expect a formatting template to be applied to handle the render. I am assuming this isn't a multi-page form you have, but I think things still apply.

As of Freeform 3.13.11 (and of course in v4), we added a `data-skip-html-reload` form attribute option to bypass HTML reload for AJAX forms when not using the render method. I wonder if you can try adding this to the form and see if that resolves the issue for you. If the error persists, can you try assigning a custom temporary formatting template to the form and see if that does it (and keep the `data-skip-html-reload` form attribute option)? 🙂

**Comment by thisisjamessmith** [comment]
Thanks Kelsey, yes this fixes the problem. Good to note that this extra attribute also fixes another problem where all my AJAX submissions were going into Spam with the reason marked as "Captcha Failure".

**Comment by kjmartens** [comment]
Thanks @thisisjamessmith. I will update the documentation to be clearer about using this. 🙂

**Comment by thisisjamessmith** [comment]
ack, sorry I spoke too soon, this doesn't actually fix my reCAPTCHA problem. (Everything is going into spam when submitting via AJAX). Should I open a new issue?

**Comment by thisisjamessmith** [comment]
This happens even when setting the spam threshold to 0.0, so it doesn't seem to be a genuine reCAPTCHA score problem.

**Comment by kjmartens** [comment]
@thisisjamessmith What does the exact reason say in the Spam Folder? Freeform provides a "Spam Reason" column in the Spam index page and more details in the individual detail. 🙂

**Comment by thisisjamessmith** [comment]
Yes, it literally just says "Captcha Failure" next to each one. I've discovered now that the hidden `g-recaptcha-response` field is not getting populated until after I click submit for the first time. If I click submit a second time, the input is populated and everything succeeds. Am I supposed to somehow trigger the grecaptcha.ready() function myself from my own AJAX routine?
